'use strict'
var isHash = /^[a-z\d]{5,7}$/
var isNumber = require('./number')
/**
 * @id isHash
 * @function isHash
 * Checks is a string looks like a hash generated by the [`hash`](#hash) utility
 * @param {string} val - the string to check
 * @returns {boolean} looksLikeHash - `true` if `val` looks like a hash, `false` otherwise
 */
module.exports = (val) => !isNumber(val) && isHash.test(val)
